### ISSUE TITLE
wro4j does not work behind a RequestDispatcher.include 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#121]
```

We're working on a far-future expiry solution which includes making a hash of 
servlet resources. These hashes are included in resource URLs and will 
automatically change when resources are updated.

We want this solution to work well with WRO, but we've found that Wro doesn't 
handle being included in a RequestDispatcher.include().

What steps will reproduce the problem?
1. Configure a WroFilter under /wro/* with a group all.js
2. In /index.jsp, get a RequestDispatcher for "/wro/all.js"
3. Perform a include(req, res) on the RequestDispatcher.
4. Observe that Wro fails with an InvalidGroupNameException ("there is no such 
group 'index')

What is the expected output? What do you see instead?
Wro should look for the request attribute 'javax.servlet.include.servlet_path' 
and use that instead of request.getServletURI if the attribute is present.

What version of the product are you using? On what operating system?
1.2.7 on a Mac

Please provide any additional information below.

```

Original issue reported on code.google.com by `eir...@gmail.com` on 30 Aug 2010 at 11:12

**Comment by ashutoshmimani** [comment]
@alexo am trying to use wro4j behind a requestDispatcher, but it doesn't seem to be working right. I'm using wro4j version 1.8.0 with tomcat 8.

I make the following request:
${pageContext.request.servletContext.getRequestDispatcher("/res/css/mobileCommonCritical.css").include(pageContext.request, pageContext.response)}

wro4j filter is configured for /res/css/*

The first issue I face is that in getGroupName method of DefaultGroupExtractor, the includeUriPath returns "/res" and not "/res/css/mobileCommonCritical.css". Should it be fetching value from "javax.servlet.include.request_uri" instead of "javax.servlet.include.servlet_path"?

The other thing is the call to getResourceType in DefaultGroupExtractor does not consider the requestDispatcher include possibility. It fetches type based on original request uri only.

Are these valid issues? Or am I making the request dispatcher call wrong which is messing up wro4j?

**Comment by ashutoshmimani** [comment]
Further, the ResourceBundleProcessor uses the response OutputStream to write the output, so the jsp that did the include cannot write to the response.
Is support for RequestDispatcher.include really working? Are there certain limitations?
