### ISSUE TITLE
Support Literate CoffeeScript

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#922]
```
Besides being used as an ordinary programming language, CoffeeScript may also 
be written in "literate" mode. If you name your file with a .litcoffee (or 
.coffee.md) extension, you can write it as a Markdown document — a document 
that also happens to be executable CoffeeScript code. The compiler will treat 
any indented blocks (Markdown's way of indicating source code) as code, and 
ignore the rest as comments. 

It would be nice if we can integrate this into wro4j as well.

Could be "litCoffeeScript" instead of "coffeeScript" for the processor 
definition (ideally with autodetection based on file-extension where 
applicable).

I am not sure if this can be passed as an option to the upstream CoffeeScript 
compiler JS, or if the Markdown stripping has to happen in a pre-processor step 
on our end.
```

Original issue reported on code.google.com by `thilopl...@googlemail.com` on 5 Mar 2015 at 1:20

**Comment by thiloplanz** [comment]
I have started to implement this. It is in fact, as simple as calling `CoffeeScript#setOptions("literate")`. The result works well.

However, I am not sure how exactly this should be done. 

I think it should be integrated into the existing `RhinoCoffeeScriptProcessor` and `NodeCoffeeScriptProcessor` (as opposed to making separate "LiterateCoffeeScriptProcessors"). And these two should decide if the input is literate or not automatically and on a per-input basis (as opposed to adding some global configuration). 

This can be done by looking at the file name extension. `.coffee.md` and `.litcoffee` would trigger it, otherwise it is assumed to be "normal" CoffeeScript. What is a good way to get to the file name extension? The `process` method has a `Resource` input, but it is optional and is `resource.getUri().endsWith()` a good idea?

Also, the options of CoffeeScript are set on pooled objects. We need to set the literate option independently of other pre-existing options and finally restore it to the old setting before returning it to the object pool, right?

**Comment by alexo** [comment]
@thiloplanz   thanks for this update.
I would rather create another processor which would configure the CoffeeScript to use literate mode. Making assumption about file extensions is something I would like to avoid, since it could not be the case for everybody. Also, it is always possible to use ExtensionAwareProcessorDecorator which does exactly the same thing.

**Comment by thiloplanz** [comment]
Okay. I have pushed a commit (see above) that adds a new "literateCoffeeScript" processor that chooses between "rhinoLiterateCoffeeScript" and "nodeLiterateCoffeeScript".  Please have a look.

**Comment by alexo** [comment]
LGTM. Thank you very much! 
Could you create a PR?

**Comment by alexo** [comment]
Thanks to @thiloplanz for the contribution!
